In [1]:
import torch 
import torch.nn as nn 

In [2]:
'''
1.self attention is a mechanism in transformers that is used to compute more efficient input representations by allowing each position in a sequence to interact with and weigh
the importance of all other positions within the same sequence 
2. The "self" in self attention ?
    >ability to compute attention weights by relating different positions within a single input sequence.
    >assesses and learns the relationship and dependencies between various parts of the inputs itself such as word in a senctence or pixels in an image 
what is the main goal of self-attention ?
    >compute a context vector for each input element, that combines information from all other input elements. 
    >importance or contribution of each input element for computing is determined by attention weights
    >when computing attention weights are calculated with respect to input element, and all other inputs. 
context vector: 
context vector is an embedding that contains information about all other inputs elements. It can be interpreted as an enriched embedding vector
what is the use of context vector? 
    > to create enriched representation of each elements in an input sequence like a sentence by incorporation information from all other elements in the sequence
    >helps to understand realtionsship and relevance of words in a sentecne to each other. 
    >Later we will add trainable weights that help an LLM learng to consturct these context vectors so that they are relevant for the LLM to generate the next token
'''

'\n1.self attention is a mechanism in transformers that is used to compute more efficient input representations by allowing each position in a sequence to interact with and weigh\nthe importance of all other positions within the same sequence \n2. The "self" in self attention ?\n    >ability to compute attention weights by relating different positions within a single input sequence.\n    >assesses and learns the relationship and dependencies between various parts of the inputs itself such as word in a senctence or pixels in an image \nwhat is the main goal of self-attention ?\n    >compute a context vector for each input element, that combines information from all other input elements. \n    >importance or contribution of each input element for computing is determined by attention weights\n    >when computing attention weights are calculated with respect to input element, and all other inputs. \ncontext vector: \ncontext vector is an embedding that contains information about all other 

In [ ]:
'''
Attention mechanism the text generating decoder part of the network can acesss all input token selectively this mean that some input tokens are more important than others for generating 
a given output token 
This means that some input toekns are more importaant than others for genrating a given output token .

self in self attention refers to the mechanism ability to compute attention weights by relating different positions within a single input sequence . 
Learns the relationship amd dependencies between various parts of the input itself, such as sequence to sequence model where the attention might be between an input sequence and 
output sequence
'''

In [4]:
import torch 
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)


In [3]:
import torch 
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)


In [7]:
query = inputs[1] # query vector using the inputs first index 
attention = torch.empty(inputs.shape[0]) #initializing an empty torch object to store the attention weights
for i,x_i in enumerate(inputs):
    attention[i] = torch.dot(x_i,query) #calculating dot product to calculate attention weights
print(attention)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [9]:
# a dot product is essentially just a concise way of multiplying two vectors element-wise and then summing the products
res = 0
for idx,element in enumerate(inputs[0]):
    res += inputs[0][idx] * query[idx]
print(res)

tensor(0.9544)


Normalizing the vector 

In [10]:
attention_weights_tmp = attention / attention.sum()
print(attention_weights_tmp)
print("sum",attention_weights_tmp.sum())

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
sum tensor(1.0000)


In [11]:
attention_weights_2 = torch.softmax(attention,dim=0)
print(attention_weights_2)
print("sum",attention_weights_2.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
sum tensor(1.)


In [12]:
#now that we computed the normalized attention weights we are ready for the final step 
#calculating the context vector by multiplying the embedded input tokens, with the correspoding attention weights and then summing the resulting vectors 


In [14]:
query = inputs[1]
context_vector = torch.zeros(query.shape)
for idx,x_i in enumerate(inputs):
    context_vector += x_i * attention_weights_2[idx]
print(context_vector)


tensor([0.4419, 0.6515, 0.5683])
